<?php
/**
 * @file
 * Hamsters in databases.
 */
 
/**
 * Implements hook_menu().
 */
function basicform_menu() {
  $items = array();

  $items['basicform'] = array(
    'title' => t('Basic Form Example'),
    'page callback' => 'basicform_example_page',
    'access arguments' => array('access content'),
  );
   
  return $items;
}

/**
 * Implements hook_page().
 */
function basicform_example_page() {
  $form = drupal_get_form('basicform_example_form');
  $output = drupal_render($form);
  
  return $output;
}

/**
 * Implements hook_form().
 */
function basicform_example_form($form, &$form_state) {
  $form['name'] = array(
    '#title' => t('Name'),
    '#type' => 'textfield',
    '#required' => TRUE,
  );
  $form['email'] = array(
    '#title' => t('Email'),
    '#type' => 'textfield',
    '#required' => TRUE,
  );
  $form['phone'] = array(
    '#title' => t('Phone'),
    '#type' => 'textfield',
  );
  $form['message'] = array(
    '#title' => t('Message'),
    '#type' => 'textarea',
  );
  $form['send'] = array(
    '#type' => 'submit',
    '#value' => t('Send Feedback'),
  );
  
  return $form;
}

function basicform_example_form_validate($form, &$form_state) {
  $phone_number = $form_state['values']['phone'];
  $phone_number = preg_replace('/[^0-9]/', '', $phone_number);
  if (strlen($phone_number) < 10) {
    form_set_error('phone', t('You must enter a valid phone number (10 digits)'));
  }
  
  if (!valid_email_address($form_state['values']['email'])) {
    form_set_error('email', t('You must enter a valid email address.'));
  }
}

function basicform_example_form_submit($form, &$form_state) {
  drupal_set_message(t('Thank you for submitting the form.'), 'status');
}