<?php
/**
 * @file
 * Node metadata displayed in a tab next to "edit".
 */
 
/**
 * Menu item for metadata tab
 * Implements hook_menu for metadata sub-tab.
 */
function node_metadata_menu() {
  $items = array();
  
  $items['node/%node/metadata'] = array(
    'title' => 'Metadata',
    'page callback' => 'node_metadata_page',
    'page arguments' => array(1),
    'access arguments' => array('view node metadata'),
    'file' => 'node_metadata.pages.inc',
    'file path' => drupal_get_path('module', 'node_metadata') . '/includes',
    'type' => MENU_LOCAL_TASK,
  );
  
  return $items;
}

/**
 * Permission to view tab
 * Implements hook_permission for metadata view.
 */
function node_metadata_permission() {
  return array(
    'view node metadata' => array(
      'title' => t('View node metadata'),
      'description' => t('View metadata for any node.'),
    ),
  );
}