<?php
/**
 * @file
 * Fire Danger custom block creation.
 */
 
/*
 * Implements hook_block_configure().
 */
function fire_danger_block_configure($delta = '') {
  $form = array();
	  if ($delta == 'fire_danger') {
		  $form['fire_danger_level'] = array(
			'#title' => t('Fire Danger Level'),
			'#type' => 'select',
			'#options' => array(
			  'high' => t('High'),
			  'moderate' => t('Moderate'),
			  'low' => t('Low'),
			),
			'#default_value' => variable_get('fire_danger_level', 'low'),
			'#description' => t('Set the level to be displayed on the CSFD landing page.'),
			'#required' => TRUE,
		  );	
	  }
	return $form;
}

function fire_danger_block_save($delta = '', $edit = array()) {
  // This example comes from node.module.
  if ($delta == 'fire_danger') {
    variable_set('fire_danger_level', $edit['fire_danger_level']);
	
    $hml = variable_get('fire_danger_level', 'none');
  
    // Notify user.
    drupal_set_message(t('Fire Danger Level saved: %t.', array('%t' => $hml)));
  }
}
 
/**
 * Implements hook_block_info().
 */
function fire_danger_block_info() {
  $blocks = array();
  
  $blocks['fire_danger'] = array(
    'info' => t('Fire Danger Level'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function fire_danger_block_view($delta = '') {
  $block = array();
  
  $hml = variable_get('fire_danger_level', 'low');
    
  switch($delta) {
    case 'fire_danger':
      $block['subject'] = fire_danger_title($hml);
      $block['content'] = fire_danger_content($hml);
      break;
  }
  
  return $block;
}

function fire_danger_title($severity) {
    return t('Fire Danger Level');
}

function fire_danger_content($severity) {
  if ($severity == 'high') {
    $level = '<div class="high"><h3>';
    $level .= t('Fire Danger: High');
	$level .= '</h3></div>';
    return $level;
  } else if ($severity == 'moderate') {
    $level = '<div class="moderate"><h3>';
    $level .= t('Fire Danger: Moderate');
	$level .= '</h3></div>';
    return $level;
  } else if ($severity == 'low') {
    $level = '<div class="low"><h3>';
    $level .= t('Fire Danger: Low');
	$level .= '</h3></div>';
    return $level;
  } else {
    return t('');
  }
}
