<?php
/**
 * @file
 * Hello world menu routing practice.
 */
 
/**
 * Implements hook_block_menu().
 */
function hello_menu_menu() {
  $items = array();
  
  $items['hello'] = array(
    'title' => 'Hello Menu',
    'description' => 'This is where we show the variables.',
    'page callback' => 'hello_menu_simple_hello',
    'access arguments' => array('access content'),
    'menu_name' => 'main-menu',
    'weight' => 1,
  );
  
  $items['hello/simple'] = array(
    'title' => 'Simple',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -1,
  );
  
  $items['hello/variables'] = array(
    'title' => 'System Variables',
    'page callback' => 'hello_menu_system_variables',
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK,
    );
  
  $items['hello/variables/list'] = array(
    'title' => 'List',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  
  $items['hello/variables/create'] = array(
    'title' => 'Create Variable',
    'page callback' => 'hello_menu_create_variable',
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 1,
  );
  
  $items['hello/variables/delete'] = array(
    'title' => 'Delete Variable',
    'page callback' => 'hello_menu_delete_variable',
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 2,
  );
  
  $items['hello/variables/%'] = array(
    'title callback' => 'hello_menu_show_variable_title',
    'title arguments' => array(2),
    'page callback' => 'hello_menu_show_variable',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  
  return $items;
}

function hello_menu_create_variable() {
  return t('It worked!');
}

function hello_menu_delete_variable() {
  return t('It deleted!');
}

function hello_menu_show_variable_title($variable_name) {
  return t('Show Variable: @name', array('@name' => $variable_name));
}

function hello_menu_show_variable($variable_name) {
  $value = variable_get($variable_name, t('No value found for this variable.'));
  return $value;
}

function hello_menu_system_variables() {
  $variables = variable_initialize();
  $names = array_keys($variables);
  $output = '<ul>';
  foreach ($names as $name) {
    $output .= '<li>' . l($name, 'hello/variables/' . $name) . '</li>';
  }
  $output .= '</ul>';
  return $output;
}

function hello_menu_simple_hello() {
  $content = t('Hello world!');
  
  return $content;
}